language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"
install:
  - sudo apt-get install portaudio19-dev
  - python setup.py install
script:
  - cd athena/tests
  - python dependencies_test.py